services:
  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    environment:
      - ACCOUNT=<qq>
      - WSR_ENABLE=true
      - WS_URLS=["ws://llmq:8080/onebot/v11/ws"]
      - NAPCAT_GID=0
      - NAPCAT_UID=0
    restart: always
    mac_address: 92:5E:A8:1F:C3:B4
    volumes:
      - ./napcat/QQ:/app/.config/QQ
      - ./napcat/config:/app/napcat/config
    networks:
      - bot_network
    depends_on:
      - llmq

  llmq:
    image: bitfennec/llmq:latest
    container_name: llmq
    restart: always
    volumes:
      - ./config.toml:/app/config.toml
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
